# Generated by Django 4.0.4 on 2022-04-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_bid_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
