# Generated by Django 4.0.4 on 2022-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('firstCat', 'First'), ('secondCat', 'Second'), ('thirdCat', 'Third'), ('fourthCat', 'Fourth')], default='firstCat', max_length=15),
        ),
    ]
